### ISSUE TITLE
Notice period of 14 days

### ISSUE THREAD

**Issue by llrs** [cranchange/cran_histories#4]
2 weeks notice period to fix problems on CRAN:

> Dear maintainer,
> 
> Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_pkg.html>.
> 
> Please correct before 2021-03-24 to safely retain your package on CRAN.
> 
> Packages in Suggests should be used conditionally: see 'Writing R Extensions'.
> This needs to be corrected even if the missing package becomes available.
> 
> The CRAN Team

**Comment by adamhsparks** [comment]
I've had various versions of this. This is one that I kinda support. In fact, I had one once and I contacted CRAN while I was having a family medical issue and Kurt responded. I was very grateful for his supportive response. I still managed to get it fixed in the allocated time frame. The issue was a false alarm thankfully, but CRAN personnel were understanding and supportive.

OTOH, I've had the "Apparently we need to remind you..." e-mail more than once as well. Here I take issue with the tone. Not the policy. 

So overall, I don't find this to be an issue as this does indeed support the whole R ecosystem.

**Comment by llrs** [comment]
Yes, I initially filled this but then I realized this is not really an issue so I didn't move it to the discussion section. Closing it now to avoid giving it more attention to it.
